name: Docker Build and Push Latest

on: push

jobs:
  dockerBuildPush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: zcong
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: zcong/rss-watcher
          tags: latest
