name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: version tag to release
        required: true
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.18
      - name: Setup git-chglog
        uses: zcong1993/setup-bin@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: git-chglog
          repo-full: git-chglog/git-chglog
          tag-version: latest
          matcher: linux_amd64.tar.gz$
          test-cmd: git-chglog --version
      - name: update changelog
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          VERSION=${{ github.event.inputs.version }}

          git-chglog --next-tag $VERSION -o CHANGELOG.md
          git commit -am "chore: update changelog for $VERSION"
          git tag $VERSION
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
