name: goreleaser

on:
  pull_request:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.15
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: zcong
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: zcong/rss-watcher
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
